---
daemonset:
  enabled: true
  extraEnvs:
    - name: "ELASTICSEARCH_HOST"
      value: "elasticsearch-master"
    - name: "ELASTICSEARCH_PORT"
      value: "9200"
    - name: "ELASTICSEARCH_USERNAME"
      valueFrom:
        secretKeyRef:
          name: elasticsearch-master-credentials
          key: username
    - name: "ELASTICSEARCH_PASSWORD"
      valueFrom:
        secretKeyRef:
          name: elasticsearch-master-credentials
          key: password

  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
      output.elasticsearch:
        host: '${NODE_NAME}'
        hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
      setup.template.overwrite: true
      setup.template.settings:
        index.number_of_shards: 1
        index.number_of_replicas: 0
