---
replicaCount: 1

es:
  uri: http://elasticsearch-master:9200
  cluster_settings: true

extraEnvSecrets:
  ES_USERNAME:
    secret: elasticsearch-master-credentials
    key: username
  ES_PASSWORD:
    secret: elasticsearch-master-credentials
    key: password
