---

global:
  storageClass: standard-rwo
  postgresql:
    auth:
      postgresPassword: admin
      username: admin
      password: admin
      database: kong

primary:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

  persistence:
    enabled: true
    storageClass: standard-rwo
    size: 8Gi

readReplicas:
  replicaCount: 0

# networkPolicy:
#   enabled: true
#   metrics:
#     enabled: true

metrics:
  enabled: true
