---
# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "1G"

imageTag: "7.17.3"
replicas: 1

extraEnvs:
  - name: "NODE_OPTIONS"
    value: "--max-old-space-size=1800"
  - name: "ELASTICSEARCH_USERNAME"
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: username
  - name: "ELASTICSEARCH_PASSWORD"
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: password

kibanaConfig:
  kibana.yml: |
    xpack.monitoring.ui.container.elasticsearch.enabled: true
    server.basePath: /kibana
    server.rewriteBasePath: true
    server.port: 5601
    server.host: 0

healthCheckPath: "/kibana/app/kibana"
