---
# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "1G"

imageTag: "7.17.3"
replicas: 1

kibanaConfig:
  kibana.yml: |
    xpack.monitoring.ui.container.elasticsearch.enabled: true
    elasticsearch.username: admin
    elasticsearch.password: admin
    server.basePath: /kibana
    server.rewriteBasePath: true
    server.port: 5601
    server.host: 0

healthCheckPath: "/kibana/app/kibana"
