---
# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"

imageTag: "7.17.3"
replicas: 1

kibanaConfig:
  kibana.yml: |
    xpack.monitoring.ui.container.elasticsearch.enabled: true
    elasticsearch.username: admin
    elasticsearch.password: admin
