---

env:
  database: "off"
  "declarative_config": "/usr/local/kong/declarative/kong.yml"
  "admin_listen": "0.0.0.0:8001, 0.0.0.0:8444 ssl"

resources:
  requests:
    cpu: 250m
    memory: 1Gi
  limits:
    cpu: 1
    memory: 2Gi

deployment:
  userDefinedVolumes:
  - name: "declarative"
    configMap:
      name: "kong-declarative-rules"
  userDefinedVolumeMounts:
  - name: "declarative"
    mountPath: "/usr/local/kong/declarative/kong.yml"
    subPath: "kong.yml"

ingressController:
  enabled: false

admin:
  useTLS: false
