---

env:
  database: "off"
  "declarative_config": "/usr/local/kong/declarative/kong.yml"
  "admin_listen": "0.0.0.0:8001"

resources:
  requests:
    cpu: 250m
    memory: 1Gi
  limits:
    cpu: 1
    memory: 2Gi

deployment:
  kong:
    enabled: true
  userDefinedVolumes:
  - name: "declarative"
    configMap:
      name: "kong-declarative-rules"
  userDefinedVolumeMounts:
  - name: "declarative"
    mountPath: "/usr/local/kong/declarative/kong.yml"
    subPath: "kong.yml"

admin:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
  tls:
    enabled: false

ingressController:
  enabled: false
