---
auth:
  username: admin
  existingPasswordSecret: rabbitmq-credentials

resources:
  requests:
    cpu: "300m"
    memory: "256M"
  limits:
    cpu: "1000m"
    memory: "1G"

replicaCount: 1

metrics:
  enabled: true
