---
antiAffinity: "soft"

# Shrink default JVM heap.
# esJavaOpts: "-Xmx128m -Xms128m"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "300m"
    memory: "2G"
  limits:
    cpu: "1000m"
    memory: "4G"

volumeClaimTemplate:
  storageClassName: "elasticsearch-ssd"
  resources:
    requests:
      storage: "2Gi"

imageTag: "7.17.3"
replicas: 1

esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false
    xpack.monitoring.collection.enabled: true
    discovery.type: single-node

extraEnvs:
- name: cluster.initial_master_nodes
  value: null
- name: "ELASTIC_USERNAME"
  valueFrom:
    secretKeyRef:
      name: elasticsearch-master-credentials
      key: username
- name: "ELASTIC_PASSWORD"
  valueFrom:
    secretKeyRef:
      name: elasticsearch-master-credentials
      key: password

labels:
  cluster: elasticsearch
